"""breeds add kind drop code group

Revision ID: 02ee8bc295d4
Revises: 20260217222914
Create Date: 2026-02-25 22:34:34.375888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02ee8bc295d4'
down_revision: Union[str, Sequence[str], None] = '20260217222914'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_breeding_pets_breeding_id'), 'breeding_pets', ['breeding_id'], unique=False)
    op.create_index(op.f('ix_breeding_pets_pet_id'), 'breeding_pets', ['pet_id'], unique=False)
    op.create_index(op.f('ix_breedings_user_id'), 'breedings', ['user_id'], unique=False)
    
    op.add_column('breeds', sa.Column('kind', sa.String(length=10), nullable=True))

    # Backfill all existing breeds as dogs
    op.execute("UPDATE breeds SET kind = 'dog' WHERE kind IS NULL")

    # Now enforce NOT NULL
    op.alter_column('breeds', 'kind', nullable=False)
    op.create_index(op.f('ix_breeds_kind'), 'breeds', ['kind'], unique=False)
    op.drop_column('breeds', 'group')
    op.drop_column('breeds', 'code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('breeds', sa.Column('code', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('breeds', sa.Column('group', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_breeds_kind'), table_name='breeds')
    op.drop_column('breeds', 'kind')
    op.drop_index(op.f('ix_breedings_user_id'), table_name='breedings')
    op.drop_index(op.f('ix_breeding_pets_pet_id'), table_name='breeding_pets')
    op.drop_index(op.f('ix_breeding_pets_breeding_id'), table_name='breeding_pets')
    # ### end Alembic commands ###
