"""Initial migration

Revision ID: 62376807fc63
Revises: 
Create Date: 2026-01-18 20:38:21.667066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62376807fc63'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('breeds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('group', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_breeds_name'), 'breeds', ['name'], unique=True)
    op.create_table('litters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_of_litter', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remember_token', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('breed_colours',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('breed_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['breed_id'], ['breeds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_breed_colours_breed_id'), 'breed_colours', ['breed_id'], unique=False)
    op.create_table('locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address1', sa.String(length=255), nullable=False),
    sa.Column('address2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=255), nullable=False),
    sa.Column('zipcode', sa.String(length=20), nullable=False),
    sa.Column('location_type', sa.String(length=50), nullable=False, comment='Type: user or pet'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_user_id'), 'locations', ['user_id'], unique=False)
    op.create_table('pets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('breed_id', sa.Integer(), nullable=True),
    sa.Column('litter_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_puppy', sa.Boolean(), nullable=True),
    sa.Column('microchip', sa.String(length=255), nullable=True),
    sa.Column('vaccination', sa.Text(), nullable=True),
    sa.Column('health_certificate', sa.Text(), nullable=True),
    sa.Column('deworming', sa.Text(), nullable=True),
    sa.Column('birth_certificate', sa.Text(), nullable=True),
    sa.Column('has_microchip', sa.Boolean(), nullable=True),
    sa.Column('has_vaccination', sa.Boolean(), nullable=True),
    sa.Column('has_healthcertificate', sa.Boolean(), nullable=True),
    sa.Column('has_dewormed', sa.Boolean(), nullable=True),
    sa.Column('has_birthcertificate', sa.Boolean(), nullable=True),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('image_file_name', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['breed_id'], ['breeds.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['litter_id'], ['litters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pets_breed_id'), 'pets', ['breed_id'], unique=False)
    op.create_index(op.f('ix_pets_is_deleted'), 'pets', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_pets_litter_id'), 'pets', ['litter_id'], unique=False)
    op.create_index(op.f('ix_pets_location_id'), 'pets', ['location_id'], unique=False)
    op.create_index(op.f('ix_pets_user_id'), 'pets', ['user_id'], unique=False)
    op.create_table('user_contacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('phone_number1', sa.String(length=50), nullable=True),
    sa.Column('phone_number2', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('facebook', sa.String(length=255), nullable=True),
    sa.Column('youtube', sa.String(length=255), nullable=True),
    sa.Column('twitter', sa.String(length=255), nullable=True),
    sa.Column('linkedin', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_contacts_location_id'), 'user_contacts', ['location_id'], unique=False)
    op.create_index(op.f('ix_user_contacts_user_id'), 'user_contacts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_contacts_user_id'), table_name='user_contacts', if_exists=True)
    op.drop_index(op.f('ix_user_contacts_location_id'), table_name='user_contacts', if_exists=True)
    op.drop_table('user_contacts', if_exists=True)
    op.drop_index(op.f('ix_pets_user_id'), table_name='pets', if_exists=True)
    op.drop_index(op.f('ix_pets_location_id'), table_name='pets', if_exists=True)
    op.drop_index(op.f('ix_pets_litter_id'), table_name='pets', if_exists=True)
    op.drop_index(op.f('ix_pets_is_deleted'), table_name='pets', if_exists=True)
    op.drop_index(op.f('ix_pets_breed_id'), table_name='pets', if_exists=True)
    op.drop_table('pets', if_exists=True)
    op.drop_index(op.f('ix_locations_user_id'), table_name='locations', if_exists=True)
    op.drop_table('locations', if_exists=True)
    op.drop_index(op.f('ix_breed_colours_breed_id'), table_name='breed_colours', if_exists=True)
    op.drop_table('breed_colours', if_exists=True)
    op.drop_index(op.f('ix_users_email'), table_name='users', if_exists=True)
    op.drop_table('users', if_exists=True)
    op.drop_table('litters', if_exists=True)
    op.drop_index(op.f('ix_breeds_name'), table_name='breeds', if_exists=True)
    op.drop_table('breeds', if_exists=True)
    # ### end Alembic commands ###
